name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90
    resources:
      limits:
        memory: 8GB
      requests:
        memory: 4GB

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-11-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev wget \
          lld  # افزودن LLD اینجا

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/.android
        touch $HOME/.android/repositories.cfg
        
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip /tmp/cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Accept licenses and install packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-31" "build-tools;34.0.0" "platform-tools" "ndk;25.2.9519653"

    - name: Fix Aidl path
      run: |
        AIDL_PATH=$(find $ANDROID_SDK_ROOT/build-tools -name aidl | head -n 1)
        echo "AIDL found at: $AIDL_PATH"
        sudo ln -sf $AIDL_PATH /usr/bin/aidl

    - name: Build APK
      run: |
        buildozer android clean  # تمیز کردن ساخت‌های قبلی
        buildozer -v android release 2>&1 | tee build.log
        
        # بررسی وجود فایل APK
        if ls ./bin/*.apk 1> /dev/null 2>&1; then
          echo "APK generated successfully"
        else
          echo "APK generation failed! Check build.log"
          cat build.log
          exit 1
        fi

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: |
          ./bin/*.apk
          ./.buildozer/android/platform/build-*/dists/*/build/outputs/apk/*/*.apk
        retention-days: 3
