name: Build APK (Fixed SDK Path)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-11-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev wget

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Install Android SDK (New Structure)
      run: |
        mkdir -p $HOME/.android
        touch $HOME/.android/repositories.cfg
        
        # Download command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O /tmp/cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip /tmp/cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        
        # Set environment variables
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Install Android packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-31" "build-tools;34.0.0" "platform-tools" "ndk;25.2.9519653"

    - name: Configure Buildozer paths
      run: |
        # Create symlink to satisfy Buildozer's expected path
        mkdir -p $HOME/.buildozer/android/platform
        ln -s $HOME/android-sdk $HOME/.buildozer/android/platform/android-sdk
        
        # Create the exact path Buildozer is looking for
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        ln -s $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Build APK
      run: |
        # Fix Aidl path
        find $ANDROID_SDK_ROOT/build-tools -name aidl -exec sudo ln -sf {} /usr/bin/aidl \;
        
        # Build with debug info
        buildozer -v android release 2>&1 | tee build.log || {
          echo "Build failed, checking log..."
          cat build.log
          exit 1
        }

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: ./bin/*.apk
        retention-days: 3
